### ISSUE TITLE
Long read actions cause UI freezes

### ISSUE THREAD

**Issue by trespasserw** [TanVD/Grazi#20]
It looks like this: a UI thread wants to perform a modification, but can't acquire the write lock because a background thread is performing some long activity under a read lock.

```
"AWT-EventQueue-0 2019.3#IU-193.SNAPSHOT IDEA, eap:true, os:Linux 5.0.0-16-generic, java-version:JetBrains s.r.o 11.0.3+12-b304.2 2019.3#IU-193.SNAPSHOT IDEA, eap:true, os:Linux 5.0.0-16-generic, java-version:JetBrains s.r.o 11.0.3+12-b304.2" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.openapi.application.impl.ReadMostlyRWLock@6a13e25c
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.writeLock(ReadMostlyRWLock.java:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1170)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
	at com.intellij.codeInsight.actions.MultiCaretCodeInsightAction.lambda$actionPerformedImpl$1(MultiCaretCodeInsightAction.java:50)
	at com.intellij.codeInsight.actions.MultiCaretCodeInsightAction$$Lambda$7733/0x0000000101f84c40.run(Unknown Source)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.actions.MultiCaretCodeInsightAction.actionPerformedImpl(MultiCaretCodeInsightAction.java:50)
	at com.intellij.codeInsight.actions.MultiCaretCodeInsightAction.actionPerformed(MultiCaretCodeInsightAction.java:46)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:590)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:643)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$4092/0x0000000102d2f040.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:642)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:508)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:396)
	at com.intellij.ide.IdeEventQueue$$Lambda$813/0x0000000100dbdc40.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.desktop@11.0.3/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.3/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.3/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.3/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.3/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.3/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

"JobScheduler FJ pool 1/7" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at java.base@11.0.3/java.lang.Class.getSuperclass(Native Method)
	at java.base@11.0.3/java.util.EnumMap.isValidKey(EnumMap.java:316)
	at java.base@11.0.3/java.util.EnumMap.get(EnumMap.java:243)
	at morfologik.stemming.DictionaryMetadata.isConvertingCase(DictionaryMetadata.java:138)
	at morfologik.speller.Speller.areEqual(Speller.java:601)
	at morfologik.speller.Speller.ed(Speller.java:562)
	at morfologik.speller.Speller.cuted(Speller.java:635)
	at morfologik.speller.Speller.findRepl(Speller.java:517)
	at morfologik.speller.Speller.findRepl(Speller.java:523)
	at morfologik.speller.Speller.findRepl(Speller.java:523)
	at morfologik.speller.Speller.findRepl(Speller.java:523)
	at morfologik.speller.Speller.findRepl(Speller.java:523)
	at morfologik.speller.Speller.findReplacementCandidates(Speller.java:430)
	at morfologik.speller.Speller.findReplacements(Speller.java:357)
	at org.languagetool.rules.spelling.morfologik.MorfologikSpeller.getSuggestions(MorfologikSpeller.java:103)
	at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.getSuggestionsFromSpellers(MorfologikMultiSpeller.java:212)
	at org.languagetool.rules.spelling.morfologik.MorfologikMultiSpeller.getSuggestionsFromDefaultDicts(MorfologikMultiSpeller.java:246)
	at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.getRuleMatches(MorfologikSpellerRule.java:243)
	at org.languagetool.rules.en.AbstractEnglishSpellerRule.getRuleMatches(AbstractEnglishSpellerRule.java:99)
	at org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule.match(MorfologikSpellerRule.java:146)
	at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:814)
	at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1255)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1189)
	at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1152)
	at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:782)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:726)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:702)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:693)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:652)
	at org.languagetool.JLanguageTool.check(JLanguageTool.java:636)
	at tanvd.grazi.grammar.GrammarEngine$getFixesSmall$1$allFixes$1.invoke(GrammarEngine.kt:50)
	at tanvd.grazi.grammar.GrammarEngine$getFixesSmall$1$allFixes$1.invoke(GrammarEngine.kt:10)
	at tanvd.grazi.utils.UtilsKt.tryRun(Utils.kt:14)
	at tanvd.grazi.grammar.GrammarEngine$getFixesSmall$1.invoke(GrammarEngine.kt:50)
	at tanvd.grazi.grammar.GrammarEngine$getFixesSmall$1.invoke(GrammarEngine.kt:10)
	at tanvd.grazi.utils.UtilsKt.buildSet(Utils.kt:56)
	at tanvd.grazi.grammar.GrammarEngine.getFixesSmall(GrammarEngine.kt:45)
	at tanvd.grazi.grammar.GrammarEngine.access$getFixesSmall(GrammarEngine.kt:10)
	at tanvd.grazi.grammar.GrammarEngine$getFixes$1.invoke(GrammarEngine.kt:37)
	at tanvd.grazi.grammar.GrammarEngine$getFixes$1.invoke(GrammarEngine.kt:10)
	at tanvd.grazi.utils.UtilsKt.buildSet(Utils.kt:56)
	at tanvd.grazi.grammar.GrammarEngine.getFixes(GrammarEngine.kt:22)
	at tanvd.grazi.grammar.GrammarEngine.getFixes$default(GrammarEngine.kt:22)
	at tanvd.grazi.grammar.SanitizingGrammarChecker.check(SanitizingGrammarChecker.kt:65)
	at tanvd.grazi.grammar.SanitizingGrammarChecker.check$default(SanitizingGrammarChecker.kt:25)
	at tanvd.grazi.grammar.SanitizingGrammarChecker.check(SanitizingGrammarChecker.kt:23)
	at tanvd.grazi.grammar.SanitizingGrammarChecker.check$default(SanitizingGrammarChecker.kt:23)
	at tanvd.grazi.ide.language.CommentsSupport$check$1.invoke(CommentsSupport.kt:19)
	at tanvd.grazi.ide.language.CommentsSupport$check$1.invoke(CommentsSupport.kt:12)
	at tanvd.grazi.utils.UtilsKt.buildSet(Utils.kt:56)
	at tanvd.grazi.ide.language.CommentsSupport.check(CommentsSupport.kt:17)
	at tanvd.grazi.ide.language.LanguageSupport.getFixes(LanguageSupport.kt:15)
	at tanvd.grazi.ide.GraziInspection.checkFile(GraziInspection.kt:50)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
	at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:227)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:321)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3847/0x0000000102b54840.run(Unknown Source)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter$$Lambda$3504/0x0000000102676440.compute(Unknown Source)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3846/0x0000000102b55440.process(Unknown Source)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3429/0x0000000102616040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1103)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3431/0x0000000102615840.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3428/0x0000000102616c40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base@11.0.3/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1039)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:58)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:58)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitRestElementsAndCleanup(LocalInspectionsPass.java:333)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:203)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:119)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$3004/0x000000010233a040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1108)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$2996/0x000000010233c040.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$2994/0x000000010233c840.run(Unknown Source)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base@11.0.3/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base@11.0.3/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base@11.0.3/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by TanVD** [comment]
We've addressed this bug during major refactoring - now LanguageSupport performs analysis per PsiElement. 
It should solve the problem with a very long activity under read lock.
