### ISSUE TITLE
UI freezes forever on a very large text file (plugin doesn't call `checkCanceled`)

### ISSUE THREAD

**Issue by vlad20012** [TanVD/Grazi#40]
I tried to edit a very large text file and the UI frozen forever (at least I managed to brew tea and did not wait any longer). I took some thread dumps: [jstack.zip](https://github.com/TanVD/Grazi/files/3362978/jstack.zip). The most interesting part is here:
<details>

  <summary>Stacktrace</summary>

```
"JobScheduler FJ pool 0/3" #47 daemon prio=4 os_prio=0 cpu=433843,28ms elapsed=589,45s tid=0x00007fcae8109000 nid=0x3658 runnable  [0x00007fcaddcd6000]
   java.lang.Thread.State: RUNNABLE
	at tanvd.grazi.utils.StringUtilsKt$splitWithRanges$1.invoke(StringUtils.kt:47)
	at tanvd.grazi.utils.StringUtilsKt$splitWithRanges$1.invoke(StringUtils.kt)
	at tanvd.grazi.utils.UtilsKt.buildList(Utils.kt:50)
	at tanvd.grazi.utils.StringUtilsKt.splitWithRanges(StringUtils.kt:34)
	at tanvd.grazi.utils.StringUtilsKt.splitWithRanges$default(StringUtils.kt:34)
	at tanvd.grazi.utils.StringUtilsKt.splitWithRanges(StringUtils.kt:31)
	at tanvd.grazi.utils.StringUtilsKt.splitWithRanges$default(StringUtils.kt:31)
	at tanvd.grazi.grammar.GrammarEngine$getFixes$1.invoke(GrammarEngine.kt:33)
	at tanvd.grazi.grammar.GrammarEngine$getFixes$1.invoke(GrammarEngine.kt:10)
	at tanvd.grazi.utils.UtilsKt.buildSet(Utils.kt:56)
	at tanvd.grazi.grammar.GrammarEngine.getFixes(GrammarEngine.kt:22)
	at tanvd.grazi.grammar.GrammarEngine.getFixes$default(GrammarEngine.kt:22)
	at tanvd.grazi.grammar.SanitizingGrammarChecker.check(SanitizingGrammarChecker.kt:65)
	at tanvd.grazi.grammar.SanitizingGrammarChecker.check$default(SanitizingGrammarChecker.kt:25)
	at tanvd.grazi.ide.language.plain.PlainTextSupport$check$1.invoke(PlainTextSupport.kt:17)
	at tanvd.grazi.ide.language.plain.PlainTextSupport$check$1.invoke(PlainTextSupport.kt:11)
	at tanvd.grazi.utils.UtilsKt.buildSet(Utils.kt:56)
	at tanvd.grazi.ide.language.plain.PlainTextSupport.check(PlainTextSupport.kt:16)
	at tanvd.grazi.ide.language.LanguageSupport.getFixes(LanguageSupport.kt:15)
	at tanvd.grazi.ide.GraziInspection.checkFile(GraziInspection.kt:50)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
	at com.intellij.psi.PsiElementVisitor.visitPlainTextFile(PsiElementVisitor.java:42)
	at com.intellij.psi.impl.source.PsiPlainTextFileImpl.accept(PsiPlainTextFileImpl.java:36)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:321)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3420/0x0000000102ba7c40.run(Unknown Source)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter$$Lambda$1902/0x0000000101d7a840.compute(Unknown Source)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3419/0x0000000102ba7840.process(Unknown Source)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3283/0x0000000102754840.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1100)
```
</details>

This code holds the read lock, so when someone will try to acquire the write lock, UI will be frozen until the read lock will be released. 
Consider using `ProgressManager.checkCanceled()` in loops more often. If the problem is in code that you doesn't control, consider using `BombedCharSequence`.

**Comment by TanVD** [comment]
Already fixed in dev
