### ISSUE TITLE
The latest version of this plugin makes program syntax parse goes wrong.

### ISSUE THREAD

**Issue by hengzhe-zhang** [TanVD/Grazi#54]
I had updated to the latest plugin, but something goes wrong. My syntax parser can't work anymore. When I disable the latest plugin, everything was back to normal.

**Comment by TanVD** [comment]
Could you please give a bit more details? What parser in what plugin does not work? Any stacktraces?

**Comment by hengzhe-zhang** [comment]
2019-07-24 23:45:00,433 [ 623851] ERROR - aemon.impl.PassExecutorService - PyCharm 2019.2 Build #PY-192.5728.105 
2019-07-24 23:45:00,433 [ 623851] ERROR - aemon.impl.PassExecutorService - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-07-24 23:45:00,433 [ 623851] ERROR - aemon.impl.PassExecutorService - OS: Windows 10 
2019-07-24 23:45:00,435 [ 623853] ERROR - aemon.impl.PassExecutorService - Plugin to blame: Grazi version: 2019.2-3.stable 
2019-07-24 23:45:00,435 [ 623853] ERROR - aemon.impl.PassExecutorService - Last Action: ShowLog 
2019-07-24 23:45:00,435 [ 623853] ERROR - aemon.impl.PassExecutorService - org/jetbrains/kotlin/psi/psiUtil/PsiUtilsKt 
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/psi/psiUtil/PsiUtilsKt 
at tanvd.grazi.ide.language.LanguageSupport$getTypos$2.invoke(LanguageSupport.kt:20) 
at tanvd.grazi.ide.language.LanguageSupport$getTypos$2.invoke(LanguageSupport.kt:10) 
at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:133) 
at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156) 
at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:702) 
at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:743) 
at tanvd.grazi.ide.language.LanguageSupport.getTypos(LanguageSupport.kt:22) 
at tanvd.grazi.ide.GraziInspection$buildVisitor$1.visitElement(GraziInspection.kt:129) 
at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274) 
at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:75) 
at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75) 
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:321) 
at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169) 
at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127) 
at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116) 
at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111) 
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:320)
at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133) 
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106) 
at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105) 
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591) 
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116) 
at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96) 
at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164) 
at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204) 
at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96) 
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) 
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) 
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) 
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) 
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) 
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by TanVD** [comment]
Yep, I can confirm it is a bug. We are fixing it right now.

**Comment by TanVD** [comment]
Fixed in master

**Comment by TanVD** [comment]
Release in dev

**Comment by TanVD** [comment]
Released in 2019.*-4
